-- MySQL Script generated by MySQL Workbench
-- Fri Mar 18 19:03:07 2016
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema javatest
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema javatest
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `javatest` DEFAULT CHARACTER SET latin1 ;
USE `javatest` ;

-- -----------------------------------------------------
-- Table `javatest`.`Person`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `javatest`.`Person` (
  `id` INT(100) NOT NULL AUTO_INCREMENT,
  `FirstName` VARCHAR(250) NULL DEFAULT NULL,
  `LastName` VARCHAR(250) NULL DEFAULT NULL,
  `Email` VARCHAR(250) NULL DEFAULT NULL,
  `Password` VARCHAR(250) NULL DEFAULT NULL,
  `UserName` VARCHAR(250) NULL DEFAULT NULL,
  `testcolumnDeleteitlater` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
